repos:
  # Black: Code-Formatierung
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: ["--check", "--diff"]

  # isort: Import-Sortierung
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--check-only", "--diff"]

  # Pylint: Codequalität

  # Pylint via local hook using your venv
  - repo: local
    hooks:
      - id: pylint
        name: pylint (venv)
        entry: .venv/bin/pylint
        language: system
        types: [ python ]
        args:
          - "--rcfile=pyproject.toml"
          - -j
          - "0"
        require_serial: true
        files: ^src/


  # MyPy: Typprüfung
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        additional_dependencies:
          - types-setuptools
        args: []

  # Standard-Hooks für sauberen Code
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=6000"]          # ~6 MB
        exclude: "^tests/fixtures/.*$"  # erlaubt große Dateien nur in tests/fixtures
