name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install system packages for Qt (EGL/X11) & headless run
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libegl1 \
          libgl1 \
          libopengl0 \
          libxkbcommon0 \
          libxkbcommon-x11-0 \
          libxcb1 \
          libxcb-cursor0 \
          libxcb-icccm4 \
          libxcb-keysyms1 \
          libxcb-render-util0 \
          libxcb-shape0 \
          libxcb-xfixes0 \
          libx11-6 \
          libdbus-1-3 \
          xvfb

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
        pip install pre-commit

    - name: Run pre-commit hooks
      run: pre-commit run --all-files --hook-stage manual --show-diff-on-failure --color always

    - name: Run tests with coverage
      run: pytest --cov=src/flametrack --cov-report=xml --cov-report=term

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        fail_ci_if_error: true
        verbose: true
